[project]
name = "langchain-langgraph"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "pyppeteer>=2.0.0",
    "rich>=14.2.0",
]

[dependency-groups]
dev = [
    "langchain[google-genai]",   
]
